version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/server
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/server
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy/deploy.sh
      runas: ec2-user