spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    gcp:
      storage:
        credentials:
          location: ${GCP_CREDENTIAL_LOCATION}
        project-id: ${GCP_PROJECT_ID}
        bucket: ${GCP_BUCKET_NAME}

firebase:
  credentials:
    location: ${FIREBASE_KEY_LOCATION}

app-key:
  kakao: ${KAKAO_APP_KEY}
  google: ${GOOGLE_APP_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    com.sillim.recordit: debug  # ref: https://blog.datalust.co/choosing-the-right-log-levels/