package com.sillim.recordit.task.domain;

public enum TaskRepetitionType {
	DAILY,
	WEEKLY,
	MONTHLY_WITH_DATE,
	MONTHLY_WITH_WEEKDAY,
	MONTHLY_WITH_LAST_DAY,
	YEARLY_WITH_DATE,
	YEARLY_WITH_WEEKDAY,
	YEARLY_WITH_LAST_DAY,
}
